### ISSUE TITLE
HowTo install node-raumserver on Raspberry Pi 3?

### ISSUE THREAD

**Issue by Dom-Perignon** [ChriD/node-raumserver#12]
Hallo @ChriD ,

as the C++-raumserver will be discontinued, is there any HowTo guide for newbies in NodeJS and Raspberry how to install the node-raumserver on a Raspberry PI 3? I'm very eager to use this tool but I have some issues installing the C++-raumserver on my RP3 (with runing KNX IP gateway and openhab2 on it) and don't want to invest here more time.

Thanks
Dom-Perignon

**Comment by ChriD** [comment]
First of all you have to install nodeJs.
```
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt install nodejs
```

Then create a directory wherer the node-raumsever should be installed , 'cd' into that directory and install node-raumserver. You may create a "log" directory
`npm install node-raumserver`

Then start it
`node node_modules/node-raumserver/test.js`

Currently there is no option for setting the port its fixed at 8080.
In future this will be a setting of course and maybe an executable so that above steps are not needed anmore. But for now. Do it like described above.   
The requests are nearly the same as from the C++ version only the return looks different and some are not ported yet. But you may check the  `node_modules\node-raumserver\test\index.html`. This is a test webinterface for testing the requests (you have to change the host ip in the index.js file if you want to test)

**Comment by Dom-Perignon** [comment]
Thanks for your quick response.
I followd your steps as follows:
creating dirctory /etc/raumserver
Creating directory /ect/raumserver/log

When starting test.js I'm getting followin error:
`error: uncaughtException: listen EADDRINUSE :::8080 date=Thu Mar 30 2017 14:38:4                                                                                                                                                             1 GMT+0200 (CEST), pid=20876, uid=1000, gid=1000, cwd=/raumserver, execPath=/usr                                                                                                                                                             /bin/nodejs, version=v7.8.0, argv=[/usr/bin/nodejs, /raumserver/node_modules/nod                                                                                                                                                             e-raumserver/test.js], rss=40247296, heapTotal=19718144, heapUsed=14226152, exte                                                                                                                                                             rnal=489701, loadavg=[0.72900390625, 0.39453125, 0.18994140625], uptime=97414
Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at Server._listen2 (net.js:1265:14)
    at listen (net.js:1301:10)
    at Server.listen (net.js:1392:7)
    at Raumserver.startHTTPServer (/raumserver/node_modules/node-raumserver/lib/                                                                                                                                                             lib.raumserver.js:74:29)
    at Raumserver.init (/raumserver/node_modules/node-raumserver/lib/lib.raumser                                                                                                                                                             ver.js:54:14)
    at Object.<anonymous> (/raumserver/node_modules/node-raumserver/test.js:7:12                                                                                                                                                             )
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
`
Is that a problem?
How can I access the test webinterface? I went to
http://[IP of RP3]:8080/raumserver/node_modules/node-raumserver/test/index.html
and
http://[IP of RP3]:8080/node_modules/node-raumserver/test/index.html
but received an 404 error both times :-( What's the problem?

Thanks in advance
Dom-Perignon

**Comment by ChriD** [comment]
> Is that a problem?

`listen EADDRINUSE :::8080`
The port 8080 is already in use by another program, so raumserver cant use it. Thats a problem because it cant listen to any requests.
Currently (as i mentioned before) you can not change th raumserver port. So i think openHab2 is using the port 8080. You can change the port in openHab or you'll have to wait until the raumserver will have a settings file. (May take a month or two)

> How can I access the test webinterface?  

The "test webinterface" is only a "standalone" html file you can open with any browser, its not reachable via the raumserver webserver. You only have to open  the index file in a browser as a local file (doublecklick on it?)
But first you have to change the hostIp in the index.js filw to the ip of the machine (RPI) where the raumserver runs

**Comment by Dom-Perignon** [comment]
OK, correct, openhab2 was running on 8080. I changed that and now it works! Great.
Two more questions:
1. How can I get this service running automitically in the background even after rebooting the system?
2. I want to use the raumserver together with the Amazon Echo Dot and openhab2. What commands do I need in order to play music from Spotify oder Radio Stations from TuneIn?
Looking forward touse this tool!

**Comment by ChriD** [comment]
1. http://stackoverflow.com/questions/21542304/start-node-js-app-on-boot
You may try the second answer of the post linked above or create a init.d script. There are a lot of sources on the net which will describe how to do this.

2. The simplest thing would be to create a playlist with the raumfeld app where you put in the radio station or anything else you would like to play. This playlist can be loaded by using the "loadPlaylist" request (**be aware that the load playlist request is not yet implemented** in the node-raumserver. This will be the next thing implemented because the kernel already supports it. Maybe i will code it this weekend. So you'll have to wait for the next version)  

I will inform you here if the next version is ready and provide you a sample how to load a playlist and start playing it. I do not have Spotify so i can't give you any advice for that.

**Comment by ChriD** [comment]
@Dom-Perignon 
Well i have updated the node-raumserver today. 
If you jump into the directory you installed the server you can make` npm update` and you will get the latest release. With this release you can do something like this:
`http://10.0.0.10:8080/raumserver/controller/loadPlaylist?id=RockNRoll`

So in fact to play a TuneIn Station you should store it in a playlist. eg. "Radio1" and then call
`http://10.0.0.10:8080/raumserver/controller/loadPlaylist?id=Radio1`

There is the ability to load the TuneIn station directly without creating a playlist, but for this you would have to know the exact id of the station given by the raumfeld media server. This would look like this:
`http://10.0.0.10:8080/raumserver/controller/loadSingle?id=0/RadioTime/LocalRadio/s-s177755`

**Comment by Dom-Perignon** [comment]
OK, cool, Thanks! I will test it out and give you feedback

**Comment by RafaelHepe** [comment]
Habe den Ordner /etc/raumserver und /etc/raumserver/log erstellt und  bekomme immer diese Nachricht beim Installationsversuch:
pi@raspberrypi:~ $ npm install node-raumserver
/home/pi
└── node-raumserver@0.0.10 

npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

Was mache ich falsch?

**Comment by ChriD** [comment]
Das sind nur warnings oder? Er wurde trotzdem installiert.
