### ISSUE TITLE
Raumserver installer application still available?

### ISSUE THREAD

**Issue by tobe2bcon** [ChriD/node-raumserver#95]
Hi,

I would like to manage my Raumfeld systems (controller and One S) by my ioBroker smart home system. I understood that SSH has to be opened on Raumfeld using your installer application. However all links here on github as well as on different community web sites (e.g. openHAB) show error 404. 

Does this mean, I cannot use raumserver anymore and that there is no way to control my Raumfeld systems?

Thank you for your answer in advance.

Best, Thomas

**Comment by kojak-le** [comment]
Hello Thomas,
SSH access is not required for the node-raumserver. It is not installed on the Raumfeld device. If you need SSH access for ioBroker, you can download the file here:
https://github.com/ChriD/Raumserver/blob/master/sshAccess/48fab7623bce0c903d5fe53dd681bb163eba85ae
Click Raw button and save File.
To activate SSH, you need a compatible Raumfeld firmware.

Best regards, Kojak

**Comment by ChriD** [comment]
@tobe2bcon 
The RaumserverInstaller was the installer tool for the old version (traumserver) of the raumserver which could have been installed on aby raumfeld device.
Since SSH is disabled on the RF devices now, you should forget the installer and use the "node-raumserver"  instead.
You can install node-raumserver in any nodeJs environment and then use it to control your raumfeld system. Its not possible anymore to install node-raumserver on a raumfeld device

**Comment by tobe2bcon** [comment]
Many thanks for your immediate response and the excellent explanations. I'll have a try.
